# Generated by Django 6.1 on 2026-08-18 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mms_app", "0005_user_two_factor_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount Paid"
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("AIRTEL", "Airtel Money (Lipa Namba)"),
                            ("MPESA", "Vodacom M-Pesa"),
                            ("TIGOPESA", "Tigo Pesa / Yas"),
                            ("HALOPESA", "Halopesa"),
                            ("NMB", "NMB Bank Direct Deposit"),
                        ],
                        default="AIRTEL",
                        max_length=20,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Phone Number"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Reference ID"
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="External Transaction ID",
                    ),
                ),
                (
                    "nmb_account_ref",
                    models.CharField(
                        default="NMB 12345678901 - MEJAS ENTERPRISES",
                        max_length=100,
                        verbose_name="NMB Target Account",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Inasubiri (Pending)"),
                            ("SUCCESS", "Imefanikiwa (Success)"),
                            ("FAILED", "Imefeli (Failed)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Provider Response"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="azampay_transactions",
                        to="mms_app.loan",
                        verbose_name="Loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
