"""
Django settings for mms_project project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = "django-insecure-+o1a2%h1%^%%s0=oaw1f57d6vqoz6lzedvlqy-@&e#6mmfrxtd"

DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mms_app",
    "payments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # For internationalization translation
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mms_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
            "libraries": {
                "admin_kpis": "mms_app.templatetags.admin_kpis",
            },
        },
    },
]

WSGI_APPLICATION = "mms_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

import sys

if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db_test.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "postgres",
            "USER": "postgres.pvpctrtncdrbbdhjlmsv",
            "PASSWORD": "##LugunE66**",
            "HOST": "aws-0-eu-central-1.pooler.supabase.com",
            "PORT": "6543",
            "OPTIONS": {
                "sslmode": "require",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "sw"  # Default Swahili

TIME_ZONE = "Africa/Dar_es_Salaam"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("sw", _("Swahili")),
    ("en", _("English")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Custom User Model
AUTH_USER_MODEL = "mms_app.User"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# Email backend for development / console output
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- AZAMPAY & BANK INTEGRATION SETTINGS ---
AZAMPAY_APP_NAME = "MEJAS_MMS"
AZAMPAY_CLIENT_ID = os.environ.get("AZAMPAY_CLIENT_ID", "mejas_client_id")
AZAMPAY_CLIENT_SECRET = os.environ.get("AZAMPAY_CLIENT_SECRET", "mejas_client_secret")
AZAMPAY_API_KEY = os.environ.get("AZAMPAY_API_KEY", "mejas_api_key")
AZAMPAY_BASE_URL = os.environ.get("AZAMPAY_BASE_URL", "https://checkout.azampay.co.tz")

# Target Institution NMB Bank Account Details
NMB_BANK_NAME = "NMB BANK PLC"
NMB_BANK_ACCOUNT_NUMBER = "12345678901"
NMB_BANK_ACCOUNT_NAME = "MEJAS ENTERPRISES MICROFINANCE"

# --- SECURITY & SESSIONS ---
# Inactivity Session Timeout set to 20 minutes (1200 seconds)
SESSION_COOKIE_AGE = 1200
# Save and refresh the session expiration age on every user request/activity
SESSION_SAVE_EVERY_REQUEST = True
# Automatically expire session on browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Production SSL Settings (To be activated when SSL is configured on Supabase custom domains)
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# ==============================================================
# JAZZMIN MODERN ADMIN SETTINGS (Mejas Microfinance System)
# ==============================================================
JAZZMIN_SETTINGS = {
    "site_title": "Mejas MMS Admin",
    "site_header": "Mejas Microfinance",
    "site_brand": "MEJAS MMS",
    "site_logo": "logo.png",
    "site_logo_classes": "img-circle elevation-2",
    "site_icon": "logo.png",
    "welcome_sign": "Karibu kwenye Mfumo wa Mejas Microfinance",
    "copyright": "Mejas Microfinance System Ltd",
    "search_model": ["mms_app.ClientProfile", "mms_app.Loan"],
    "user_avatar": "photo",
    "topmenu_links": [
        {"name": "Tovuti ya Mwanzo", "url": "home", "permissions": []},
        {"name": "Ripoti za Kifedha", "url": "reports_menu", "permissions": ["mms_app.view_loan"]},
        {"name": "Ufuatiliaji wa Leo", "url": "daily_repayment_tracking", "permissions": ["mms_app.view_payment"]},
    ],
    "usermenu_links": [
        {"name": "Tovuti Kuu (Home)", "url": "home", "icon": "fas fa-globe"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "mms_app.ClientProfile",
        "mms_app.Loan",
        "mms_app.RepaymentSchedule",
        "mms_app.Payment",
        "mms_app.CashFlow",
        "mms_app.DailyReconciliation",
        "mms_app.Branch",
        "mms_app.User",
        "mms_app.AuditLog",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "mms_app.User": "fas fa-user-shield",
        "mms_app.ClientProfile": "fas fa-address-card",
        "mms_app.Loan": "fas fa-hand-holding-dollar",
        "mms_app.Payment": "fas fa-receipt",
        "mms_app.RepaymentSchedule": "fas fa-calendar-alt",
        "mms_app.Branch": "fas fa-building",
        "mms_app.CashFlow": "fas fa-money-bill-wave",
        "mms_app.DailyReconciliation": "fas fa-scale-balanced",
        "mms_app.AuditLog": "fas fa-history",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin_custom.css",
    "custom_js": None,
    "show_theme_chooser": True,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "mms_app.loan": "horizontal_tabs",
        "mms_app.clientprofile": "horizontal_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "default_theme_mode": "auto",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}