# Generated by Django 6.1 on 2026-08-07 09:27

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Branch Name")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Location"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO / Mkurugenzi"),
                            ("MANAGER", "Manager"),
                            ("CASHIER", "Cashier (Mhazini)"),
                            ("OFFICER", "Loan Officer"),
                            ("CLIENT", "Mteja (Client)"),
                        ],
                        default="CLIENT",
                        max_length=20,
                        verbose_name="User Role",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "nida",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="NIDA ID Number",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="mms_app.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("IN", "Ingizo (Cash In / Collection)"),
                            ("OUT", "Toleo (Cash Out / Disbursement / Expense)"),
                        ],
                        max_length=10,
                        verbose_name="Flow Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DISBURSEMENT", "Mikopo Iliyotolewa (Disbursement)"),
                            ("COLLECTION", "Marejesho ya Mikopo (Collection)"),
                            ("OFFICE_INCOME", "Mapato ya Ofisi (Office Income)"),
                            ("OFFICE_EXPENSE", "Matumizi ya Ofisi (Office Expense)"),
                        ],
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description / Maelezo"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flows",
                        to="mms_app.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_cash_flows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow",
                "verbose_name_plural": "Cash Flows",
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Address / Anwani"),
                ),
                (
                    "guarantor_name",
                    models.CharField(
                        max_length=150, verbose_name="Guarantor Full Name"
                    ),
                ),
                (
                    "guarantor_phone",
                    models.CharField(
                        max_length=20, verbose_name="Guarantor Phone Number"
                    ),
                ),
                (
                    "guarantor_nida",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Guarantor NIDA ID",
                    ),
                ),
                (
                    "guarantor_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Guarantor Address",
                    ),
                ),
                (
                    "guarantor_relationship",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Relationship to Client",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_id",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Loan ID"
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Principal Amount"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Interest Rate (%)"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(verbose_name="Duration (Installments Count)"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Kila Siku (Daily)"),
                            ("WEEKLY", "Kila Wiki (Weekly)"),
                            ("MONTHLY", "Kila Mwezi (Monthly)"),
                        ],
                        default="DAILY",
                        max_length=15,
                        verbose_name="Repayment Frequency",
                    ),
                ),
                (
                    "total_repayable",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Repayable",
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Installment Amount",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Outstanding Balance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Inayosubiri Kuidhinishwa (Pending)"),
                            ("APPROVED", "Imeidhinishwa (Approved)"),
                            ("REJECTED", "Imekataliwa (Rejected)"),
                            ("ACTIVE", "Inafanya kazi (Active)"),
                            ("COMPLETED", "Imelipwa Kamili (Completed/Paid Off)"),
                            ("OVERDUE", "Iliyochelewa (Overdue)"),
                            ("DEFAULTED", "Chechefu (Defaulted)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Application Date",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disbursement Date"
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Late Penalty Rate (%)",
                    ),
                ),
                (
                    "penalty_accumulated",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Accumulated Penalty",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="mms_app.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "CLIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "disbursed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursed_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Disbursed By",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "OFFICER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officer_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Loan Officer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount Paid"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Payment Date"
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Receipt / Transaction ID",
                    ),
                ),
                (
                    "cashier_or_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded By",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="mms_app.loan",
                        verbose_name="Loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Installment Amount",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paid Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Hajalipa (Unpaid)"),
                            ("PAID", "Amelipa (Paid)"),
                            ("OVERDUE", "Iliyochelewa (Overdue)"),
                        ],
                        default="UNPAID",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="mms_app.loan",
                        verbose_name="Loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repayment Schedule",
                "verbose_name_plural": "Repayment Schedules",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Opening Balance",
                    ),
                ),
                (
                    "total_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Cash In (Collections)",
                    ),
                ),
                (
                    "total_disbursed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Cash Out (Disbursements/Expenses)",
                    ),
                ),
                (
                    "calculated_closing",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Calculated Closing Balance",
                    ),
                ),
                (
                    "actual_cash",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Actual Physical Cash",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Difference (Actual - Calculated)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Inasubiri Kuthibitishwa (Pending Approval)"),
                            ("CONFIRMED", "Imethibitishwa (Confirmed)"),
                            ("REJECTED", "Imekataliwa (Rejected)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confirmation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmation Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="mms_app.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        limit_choices_to={"role": "CASHIER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashier_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cashier",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Reconciliation",
                "verbose_name_plural": "Daily Reconciliations",
                "unique_together": {("branch", "date")},
            },
        ),
    ]
