# Generated by Django 4.2.30 on 2026-08-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='guarantor_phone',
            field=models.CharField(max_length=50, verbose_name='Guarantor Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO / Admin'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier (Mhazini)'), ('OFFICER', 'Loan Officer'), ('CLIENT', 'Mteja (Client)')], default='CLIENT', max_length=20, verbose_name='User Role'),
        ),
    ]
