# Generated by Django 4.2.30 on 2026-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms_app', '0002_alter_clientprofile_guarantor_phone_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='guarantor_nida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guarantor NIDA ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIDA ID Number'),
        ),
    ]
