# Generated by Django 6.1 on 2026-08-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mms_app", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Two-Factor Authentication (2FA)"
            ),
        ),
    ]
